//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "routes")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub pathname: String,
    pub route: String,
    pub created_at: i64,
    pub cost_time: i64,
    pub leaved_at: i64,
    pub url: String,
    #[sea_orm(column_type = "Text")]
    pub search_obj: String,
    pub username: String,
    pub session_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
